In [115]:
#instalaciones
#%pip install numpy pandas matplotlib tabulate networkx
#%pip install openpyxl --user



In [116]:
 #importaciones:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from IPython.display import HTML, display
import tabulate
import networkx as nx
from random import random as rand
import itertools

In [117]:
np.random.seed(1)

In [118]:
def sigmoid(x):
    return 1 / ( 1 + np.exp(-x) )

def sigmoid_derivative(x):
    return x * (1 - x)

Creamos un dataset el cual consiste en un modelo el cual según distintas caracteristicas define si un auto es deportivo, clásico o familiar. Un auto puede pertenecer a dos de estas clases al mismo tiempo.

El dataset tiene 100 muestras y dentro de la capa de entrada tiene estas caracteristicas: potencia (caballos de fuerza), peso, espacio interior, puertas y consumo de combustible.

La salidas como mencionamos anteriormente son: deportivo, clásico y familiar.

In [119]:
dataset_entrenamiento = pd.read_excel('entrenamiento dataset.xlsx')
dataset_entrenamiento

potencia  peso   espacio_interior  puertas  consumo_combustible  \
0        222  1087   2404724450023640        2    12992025873523900   
1         97  2334   3480520612478050        2    11304479368667900   
2        167  2278  23702328216313300        4     1374287966624940   
3        242  1673  33540462869965200        2     7930202845077960   
4        373  1068  27863061028372900        2    13489435553129100   
5        301  1617  19064221926673500        2    11178766919175200   
6        245   901  23948469778680900        2     5132368577588990   
7         59  1083  32098947321037900        2     8472335179322190   
8        261  2236    327261828374452        2      648140860948165   
9        327  1070  32229757465487300        2    14818293898182500   
10       292  1255   3459602459571400        2      978370307039988   
11       342  1654  34563098100050600        2     9973913654986620   
12       137  2107  27942553063019200        4    11394725163987200   
13       120   723  41896397875531800        2     8685846061296170   
14       138  2423  26026856101436800        4      636900271685599   
15       364   830  28075947757968800        4    13221177331942400   
16       243  1077   4175770065047010        2      689847911902758   
17        89   798   3918581967138250        4     1011318982546450   
18       137  2298   3611665750621090        4     7243170289747390   
19       224  1631  18006806619369000        4    59784448449403400   
20       138  1434  42584478412340200        2    13621915174216800   
21       387   823  36427238986473296        2    14729194890231300   
22       215  1294   4496541019703590        4    14608346580630000   
23        75  1439  19483449139739800        4    14065554992211700   
24       383  1872   4104378172104640        4    12740473326986300   
25       122   909  19874788040291200        4      833145152028642   
26       315  1262  33466786928515300        2     5811013899879960   
27       165  2135  18714599485483200        4     9072411714138070   
28       293  1482  40440246879667000        2     7322341421709420   
29       247  1765   3921956876175030        4    63248763475798200   
30       385  1782    320730221584378        2     5534271817868250   
31       388  1405   2721549891677990        2    12255943642105700   
32       149  1760  17075009863654100        2    51142745862503104   
33       227  1478  35922863194336900        2    12705807485027700   
34       293   786  28606280480342000        4     6469466454003750   
35       335  1767  36661667984110400        4     5795220825867550   
36       197  1572   4099146977785880        4     5896030342386050   
37       197   711   4426564515008650        4    11720478073539100   
38       338  1470   4067410027177830        4     7453672098528440   
39       219  1841  26503916825156900        4      899025321703102   
40       213  2169  32649513406608100        2    14040443929009500   
41       145  2319   3993145365708570        2    11900250201912200   
42       247  1373  33869455307734400        2    11996220542505100   
43       144  1628   4117951966342180        2      827720401557119   
44       306  1952  23206261044469000        2    12567786427368800   
45       228  2231   3894140501737690        4    11360610554471400   
46       342  1463  20569078329178500        4     7400202733797090   
47       354   821  43583749709158304        2     6605388224852560   
48       399  2050  35624648291634400        2    12963914745173300   

    deportivo  clasico  familiar  
0           1        0         0  
1           0        1         0  
2           0        0         0  
3           0        0         0  
4           1        0         0  
5           0        0         0  
6           1        0         0  
7           0        1         0  
8           0        0         0  
9           1        0         0  
10          1        0         0  
11          0        0         0 

In [120]:
training_inputs = dataset_entrenamiento.iloc[:, :5]  # Primeras 5 columnas
training_outputs = dataset_entrenamiento.iloc[:, 5:]  # Últimas columnas
training_inputs = training_inputs.to_numpy()
training_outputs = training_outputs.to_numpy()

print("Shape of training_inputs:", training_inputs.shape)  # 
print("Shape of training_outputs:", training_outputs.shape)  # 

Shape of training_inputs: (49, 5)
Shape of training_outputs: (49, 3)


In [121]:
training_values = np.concatenate((training_inputs.T, training_outputs.T)).T
table = lambda arr : display(HTML(tabulate.tabulate(arr, tablefmt='html')))
table(training_values)

In [122]:
forward = lambda x, w: sigmoid(np.dot(x, w))

In [142]:
n = training_inputs.shape[1]
m = training_outputs.shape[1]
synaptic_weights=2*np.random.random((n,m))-1
display(synaptic_weights)

array([[-0.66929161,  0.85501716, -0.30446828],
       [ 0.50162421,  0.45199597,  0.76661218],
       [ 0.24734441,  0.50188487, -0.30220332],
       [-0.46014422,  0.79177244, -0.14381762],
       [ 0.92968009,  0.326883  ,  0.24339144]])

In [143]:
input_layer = training_inputs

# Genera un output haciendo la suma de los valores de input multiplicados por su peso sinaptico, y aplicandole la función sigmoide para normalizar a -1, 1
outputs = forward(input_layer, synaptic_weights)

outputs

C:\Users\48793373\AppData\Local\Temp\ipykernel_11956\2995751674.py:2: RuntimeWarning: overflow encountered in exp
  return 1 / ( 1 + np.exp(-x) )


array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 0.],
       [1., 1., 0.],
       [1., 1., 0.],
       [1., 1., 0.],
       [1., 1., 0.],
       [1., 1., 0.],
       [1., 1., 1.],
       [1., 1., 0.],
       [1., 1., 0.],
       [1., 1., 0.],
       [1., 1., 0.],
       [1., 1., 0.],
       [1., 1., 0.],
       [1., 1., 0.],
       [1., 1., 0.],
       [1., 1., 0.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 0.],
       [1., 1., 0.],
       [1., 1., 1.],
       [1., 1., 0.],
       [1., 1., 1.],
       [1., 1., 0.],
       [1., 1., 0.],
       [1., 1., 0.],
       [1., 1., 0.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 0.],
       [1., 1., 0.],
       [1., 1., 0.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 0.],
       [1., 1., 0.],
       [1., 1., 1.],
       [1., 1., 0.],
       [1., 1., 0.],
       [1., 1., 0.],
       [1., 1., 1.],
       [1., 1., 0.],
       [1., 1

In [144]:
training_outputs

array([[1, 0, 0],
       [0, 1, 0],
       [0, 0, 0],
       [0, 0, 0],
       [1, 0, 0],
       [0, 0, 0],
       [1, 0, 0],
       [0, 1, 0],
       [0, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [0, 0, 0],
       [0, 1, 0],
       [0, 0, 0],
       [0, 1, 0],
       [1, 0, 0],
       [1, 0, 0],
       [0, 0, 1],
       [0, 1, 1],
       [0, 0, 0],
       [0, 1, 0],
       [1, 0, 0],
       [1, 0, 1],
       [0, 1, 0],
       [0, 0, 1],
       [0, 0, 0],
       [1, 0, 0],
       [0, 0, 0],
       [1, 0, 0],
       [0, 0, 1],
       [0, 0, 0],
       [1, 0, 0],
       [0, 1, 0],
       [1, 0, 0],
       [1, 0, 0],
       [0, 0, 1],
       [0, 0, 1],
       [0, 0, 1],
       [1, 0, 1],
       [0, 0, 0],
       [0, 0, 0],
       [0, 1, 0],
       [1, 0, 0],
       [0, 1, 0],
       [0, 0, 0],
       [0, 0, 1],
       [1, 0, 0],
       [1, 0, 0],
       [0, 0, 0]])

In [145]:
# Calculo el error
error = training_outputs - outputs
error

array([[ 0., -1., -1.],
       [-1.,  0., -1.],
       [-1., -1.,  0.],
       [-1., -1.,  0.],
       [ 0., -1.,  0.],
       [-1., -1.,  0.],
       [ 0., -1.,  0.],
       [-1.,  0.,  0.],
       [-1., -1., -1.],
       [ 0., -1.,  0.],
       [ 0., -1.,  0.],
       [-1., -1.,  0.],
       [-1.,  0.,  0.],
       [-1., -1.,  0.],
       [-1.,  0.,  0.],
       [ 0., -1.,  0.],
       [ 0., -1.,  0.],
       [-1., -1.,  1.],
       [-1.,  0.,  0.],
       [-1., -1., -1.],
       [-1.,  0.,  0.],
       [ 0., -1.,  0.],
       [ 0., -1.,  0.],
       [-1.,  0.,  0.],
       [-1., -1.,  0.],
       [-1., -1.,  0.],
       [ 0., -1.,  0.],
       [-1., -1.,  0.],
       [ 0., -1.,  0.],
       [-1., -1.,  0.],
       [-1., -1., -1.],
       [ 0., -1., -1.],
       [-1.,  0., -1.],
       [ 0., -1.,  0.],
       [ 0., -1.,  0.],
       [-1., -1.,  1.],
       [-1., -1.,  0.],
       [-1., -1.,  0.],
       [ 0., -1.,  0.],
       [-1., -1.,  0.],
       [-1., -1.,  0.],
       [-1.,  0.

In [146]:
sigmoid_derivative(outputs)


array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0

In [151]:
epochs = 5000

for iteration in range(epochs):

    # Arranca con los valores de training
    input_layer = training_inputs

    # Genera un output haciendo la suma de los valores de input multiplicados por su peso sinaptico, y aplicandole la función sigmoide para normalizar a -1, 1
    outputs = forward(input_layer, synaptic_weights)

    # Calculo el error
    error = training_outputs - outputs

    # Ajusto los pesos en funcion al error y al resultado obtenido
    adjustments = error * sigmoid_derivative(outputs)
    synaptic_weights += np.dot(input_layer.T, adjustments)

C:\Users\48793373\AppData\Local\Temp\ipykernel_11956\2995751674.py:2: RuntimeWarning: overflow encountered in exp
  return 1 / ( 1 + np.exp(-x) )


In [152]:
print('Synaptic weights after training')
print(synaptic_weights)

print('Outputs after training: ')
print(outputs)

Synaptic weights after training
[[-0.66929161  0.85501716 -0.30446828]
 [ 0.50162421  0.45199597  0.76661218]
 [ 0.24734441  0.50188487 -0.30220332]
 [-0.46014422  0.79177244 -0.14381762]
 [ 0.92968009  0.326883    0.24339144]]
Outputs after training: 
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 0.]
 [1. 1. 0.]
 [1. 1. 0.]
 [1. 1. 0.]
 [1. 1. 0.]
 [1. 1. 0.]
 [1. 1. 1.]
 [1. 1. 0.]
 [1. 1. 0.]
 [1. 1. 0.]
 [1. 1. 0.]
 [1. 1. 0.]
 [1. 1. 0.]
 [1. 1. 0.]
 [1. 1. 0.]
 [1. 1. 0.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 0.]
 [1. 1. 0.]
 [1. 1. 1.]
 [1. 1. 0.]
 [1. 1. 1.]
 [1. 1. 0.]
 [1. 1. 0.]
 [1. 1. 0.]
 [1. 1. 0.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 0.]
 [1. 1. 0.]
 [1. 1. 0.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 0.]
 [1. 1. 0.]
 [1. 1. 1.]
 [1. 1. 0.]
 [1. 1. 0.]
 [1. 1. 0.]
 [1. 1. 1.]
 [1. 1. 0.]
 [1. 1. 0.]
 [1. 1. 0.]]


EVALUACIÓN

In [149]:
table(training_values)

In [150]:
a = 0 #@param {type:"integer"}
b = 0 #@param {type:"integer"}
c = 0 #@param {type:"integer"}
d = 0 #@param {type:"integer"}
e = 0 #@param {type:"integer"}

input_layer = np.array([a, b, c, d, e])
res = sigmoid(np.dot(input_layer, synaptic_weights))

thresh = 0.01
out = np.where(res < thresh, 0, 1)

table(out)


TypeError: 'numpy.int64' object is not iterable