In [187]:
#instalaciones
%pip install numpy pandas matplotlib tabulate networkx
%pip install openpyxl --user



Note: you may need to restart the kernel to use updated packages.
Defaulting to user installation because normal site-packages is not writeable



[notice] A new release of pip is available: 24.2 -> 24.3.1
[notice] To update, run: python.exe -m pip install --upgrade pip


Note: you may need to restart the kernel to use updated packages.



[notice] A new release of pip is available: 24.2 -> 24.3.1
[notice] To update, run: python.exe -m pip install --upgrade pip


In [188]:
 #importaciones:

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from IPython.display import HTML, display
import tabulate
import networkx as nx
from random import random as rand
import itertools

In [189]:
np.random.seed(1)

In [190]:
def sigmoid(x):
    return 1 / ( 1 + np.exp(-x) )
def sigmoid_derivative(x):
    return x * (1 - x)

Creamos un dataset el cual consiste en un modelo el cual según distintas caracteristicas define si un auto es deportivo, clásico o familiar. Un auto puede pertenecer a dos de estas clases al mismo tiempo.

El dataset tiene 100 muestras y dentro de la capa de entrada tiene estas caracteristicas: potencia (caballos de fuerza), peso, espacio interior, puertas y consumo de combustible.

La salidas como mencionamos anteriormente son: deportivo, clásico y familiar.

In [191]:
dataset_entrenamiento = pd.read_excel('entrenamiento dataset.xlsx')
dataset_entrenamiento

potencia  peso   espacio_interior  puertas  consumo_combustible  \
0        222  1087   2404724450023640        2    12992025873523900   
1         97  2334   3480520612478050        2    11304479368667900   
2        167  2278  23702328216313300        4     1374287966624940   
3        242  1673  33540462869965200        2     7930202845077960   
4        373  1068  27863061028372900        2    13489435553129100   
5        301  1617  19064221926673500        2    11178766919175200   
6        245   901  23948469778680900        2     5132368577588990   
7         59  1083  32098947321037900        2     8472335179322190   
8        261  2236    327261828374452        2      648140860948165   
9        327  1070  32229757465487300        2    14818293898182500   
10       292  1255   3459602459571400        2      978370307039988   
11       342  1654  34563098100050600        2     9973913654986620   
12       137  2107  27942553063019200        4    11394725163987200   
13       120   723  41896397875531800        2     8685846061296170   
14       138  2423  26026856101436800        4      636900271685599   
15       364   830  28075947757968800        4    13221177331942400   
16       243  1077   4175770065047010        2      689847911902758   
17        89   798   3918581967138250        4     1011318982546450   
18       137  2298   3611665750621090        4     7243170289747390   
19       224  1631  18006806619369000        4    59784448449403400   
20       138  1434  42584478412340200        2    13621915174216800   
21       387   823  36427238986473296        2    14729194890231300   
22       215  1294   4496541019703590        4    14608346580630000   
23        75  1439  19483449139739800        4    14065554992211700   
24       383  1872   4104378172104640        4    12740473326986300   
25       122   909  19874788040291200        4      833145152028642   
26       315  1262  33466786928515300        2     5811013899879960   
27       165  2135  18714599485483200        4     9072411714138070   
28       293  1482  40440246879667000        2     7322341421709420   
29       247  1765   3921956876175030        4    63248763475798200   
30       385  1782    320730221584378        2     5534271817868250   
31       388  1405   2721549891677990        2    12255943642105700   
32       149  1760  17075009863654100        2    51142745862503104   
33       227  1478  35922863194336900        2    12705807485027700   
34       293   786  28606280480342000        4     6469466454003750   
35       335  1767  36661667984110400        4     5795220825867550   
36       197  1572   4099146977785880        4     5896030342386050   
37       197   711   4426564515008650        4    11720478073539100   
38       338  1470   4067410027177830        4     7453672098528440   
39       219  1841  26503916825156900        4      899025321703102   
40       213  2169  32649513406608100        2    14040443929009500   
41       145  2319   3993145365708570        2    11900250201912200   
42       247  1373  33869455307734400        2    11996220542505100   
43       144  1628   4117951966342180        2      827720401557119   
44       306  1952  23206261044469000        2    12567786427368800   
45       228  2231   3894140501737690        4    11360610554471400   
46       342  1463  20569078329178500        4     7400202733797090   
47       354   821  43583749709158304        2     6605388224852560   
48       399  2050  35624648291634400        2    12963914745173300   

    deportivo  clasico  familiar  
0           1        0         0  
1           0        1         0  
2           0        0         0  
3           0        0         0  
4           1        0         0  
5           0        0         0  
6           1        0         0  
7           0        1         0  
8           0        0         0  
9           1        0         0  
10          1        0         0  
11          0        0         0 

In [192]:
dataset_testeo = pd.read_excel('dataset_testeo.xlsx')
dataset_testeo

315  1007  15351422525550000  2   9205394666800980  1  0  0.1
0   235  1804  25799341934350900  4   1057368791323910  0  0    0
1   177   732   3689971687272170  2  13605511738287900  0  0    0
2    82  1906  20148890317843200  4  12270442627113200  0  1    0
3    81  1852   3063109818612380  2   7703279052387140  0  1    0
4   252  1506  16630139650177600  4   6314827992911270  0  0    0
5   294   975     20999895746892  2    555374320421198  1  0    0
6   201  1898   1555565383381840  4   8015986344809420  0  0    0
7   213  2278   3881093110072260  4   7621181492396780  0  0    1
8   233  2095  21717740641811400  2   9561405668004790  0  0    0
9    78  1908   2536055042090700  2  11832813355476800  0  1    0
10  340  1144   4284243880396770  2   1195625445638850  1  0    0
11  178  1188  36132432057705904  4   7835188465821660  0  0    1
12  178  2313  15955167885939200  4   8799269559001200  0  0    0
13  103   986  19940824694937300  4   6811509617369030  0  0    0
14   88  2004  33644352044992900  2  12885455123065100  0  1    0
15  294  1337   3231685765812500  2   5568480764332400  1  0    0
16  323  1470   2213678464123520  4  11969972417249800  1  0    0
17  385  2239   4302641993774380  2  12786953959411000  0  0    0
18  155   794   3341897867897680  2  12774075618487500  0  0    0
19   92  1950   3106898409074870  4    759422564345355  0  1    1
20   81  1993   3269729929063710  2   8738131379325610  0  1    0
21  307   996   3690366088550300  2   1087599635196380  1  0    0
22  371  2052  24358349864388000  2    772821902424467  0  0    0
23  107  1743  26946631866482700  4   8708527992178880  0  1    0
24  341  1307  21295312469253600  2   6970542801856390  1  0    0
25  169  2134  20585790176410000  4   9598558837560070  0  0    0
26  317  1150   4333117169951800  2   5446123012541140  1  0    0
27  132  1972  37186523851478600  4   1299795884570610  0  1    1
28  141   880  29713764258527000  2   5769564469866320  0  0    0
29  149  1023    218224388391997  4   1018835148831520  0  1    0
30  103  1704   2263069445311170  4    806810099545196  0  1    0
31  171  1984  16740874809716200  2  10775429488313700  0  0    0
32  134  1449  28032498766743600  2   1459433340833420  0  1    0
33  253   839  24353876459823000  4  11455702444560000  1  0    0
34  374  1720  35890304664463700  2   5353624357554900  0  0    0
35  312  1298   2633255517877440  4   9304024395080610  1  0    0
36   97  2185  20388110326789000  2  10100168523182500  0  1    0
37  177  1589  15740361851739900  4  10361774947034500  0  0    0
38  181  2345  17017488943897400  2   1181392510603830  0  0    0
39  230  1543   3538178320495700  2   7775960977317660  0  0    0
40  384  1396   2861090533668130  2   6288605654663200  1  0    0
41  193  2252  31097376333261600  2   8926756765470940  0  0    0
42  198  1876   4190013879121020  4  14564057227959400  0  0    1
43  277  1625   4471016842190110  4   6871308917508440  0  0    1
44  329   849  21506909531954200  2   1403983954928230  1  0    0
45  257  1834  34892346093003000  4  10438059500773200  0  0    1
46  391   725   2289967130211450  2   9569114216457650  1  0    0
47   98  2188   1561952998397180  4  13820414102298800  0  1    0
48  355  1656  37751359615084200  4    958603961768586  0  0    1

In [193]:
training_inputs = dataset_entrenamiento.iloc[:, :5]  # Primeras 5 columnas
training_outputs = dataset_entrenamiento.iloc[:, 5:]  # Últimas columnas

print("Shape of training_inputs:", training_inputs.shape)  # 
print("Shape of training_outputs:", training_outputs.shape)  # 

Shape of training_inputs: (49, 5)
Shape of training_outputs: (49, 3)


In [194]:
training_values = np.concatenate((training_inputs.T, training_outputs.T)).T
table = lambda arr : display(HTML(tabulate.tabulate(arr, tablefmt='html')))
table(training_values)

In [195]:
forward = lambda x, w: sigmoid(np.dot(x, w))

In [196]:
n=training_inputs.shape[1]
m=training_outputs.shape[1]
synaptic_weights=2*np.random.random((n,m))-1
display(synaptic_weights)

array([[-0.16595599,  0.44064899, -0.99977125],
       [-0.39533485, -0.70648822, -0.81532281],
       [-0.62747958, -0.30887855, -0.20646505],
       [ 0.07763347, -0.16161097,  0.370439  ],
       [-0.5910955 ,  0.75623487, -0.94522481]])

In [197]:
input_layer = training_inputs
outputs = forward(input_layer, synaptic_weights)
outputs 

C:\Users\gaetf\AppData\Local\Temp\ipykernel_19092\4196915625.py:2: RuntimeWarning: overflow encountered in exp
  return 1 / ( 1 + np.exp(-x) )


array([[0., 1., 0.],
       [0., 1., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 1., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 1., 0.],
       [0., 0., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 0., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 0., 0.],
       [0., 0

In [198]:
training_outputs

deportivo  clasico  familiar
0           1        0         0
1           0        1         0
2           0        0         0
3           0        0         0
4           1        0         0
5           0        0         0
6           1        0         0
7           0        1         0
8           0        0         0
9           1        0         0
10          1        0         0
11          0        0         0
12          0        1         0
13          0        0         0
14          0        1         0
15          1        0         0
16          1        0         0
17          0        0         1
18          0        1         1
19          0        0         0
20          0        1         0
21          1        0         0
22          1        0         1
23          0        1         0
24          0        0         1
25          0        0         0
26          1        0         0
27          0        0         0
28          1        0         0
29          0        0         1
30          0        0         0
31          1        0         0
32          0        1         0
33          1        0         0
34          1        0         0
35          0        0         1
36          0        0         1
37          0        0         1
38          1        0         1
39          0        0         0
40          0        0         0
41          0        1         0
42          1        0         0
43          0        1         0
44          0        0         0
45          0        0         1
46          1        0         0
47          1        0         0
48          0        0         0

In [199]:
# Calculo el error
error = training_outputs - outputs
error

deportivo  clasico  familiar
0         1.0     -1.0       0.0
1         0.0      0.0       0.0
2         0.0      0.0       0.0
3         0.0      0.0       0.0
4         1.0     -1.0       0.0
5         0.0     -1.0       0.0
6         1.0      0.0       0.0
7         0.0      1.0       0.0
8         0.0     -1.0       0.0
9         1.0     -1.0       0.0
10        1.0      0.0       0.0
11        0.0      0.0       0.0
12        0.0      1.0       0.0
13        0.0      0.0       0.0
14        0.0      1.0       0.0
15        1.0     -1.0       0.0
16        1.0      0.0       0.0
17        0.0      0.0       1.0
18        0.0      0.0       1.0
19        0.0     -1.0       0.0
20        0.0      1.0       0.0
21        1.0      0.0       0.0
22        1.0     -1.0       1.0
23        0.0      0.0       0.0
24        0.0     -1.0       1.0
25        0.0      0.0       0.0
26        1.0      0.0       0.0
27        0.0     -1.0       0.0
28        1.0      0.0       0.0
29        0.0     -1.0       1.0
30        0.0     -1.0       0.0
31        1.0     -1.0       0.0
32        0.0      0.0       0.0
33        1.0      0.0       0.0
34        1.0      0.0       0.0
35        0.0      0.0       1.0
36        0.0     -1.0       1.0
37        0.0     -1.0       1.0
38        1.0     -1.0       1.0
39        0.0      0.0       0.0
40        0.0     -1.0       0.0
41        0.0      0.0       0.0
42        1.0      0.0       0.0
43        0.0      1.0       0.0
44        0.0     -1.0       0.0
45        0.0     -1.0       1.0
46        1.0      0.0       0.0
47        1.0      0.0       0.0
48        0.0      0.0       0.0

In [200]:
epochs = 5000

for iteration in range(epochs):

    # Arranca con los valores de training
    input_layer = training_inputs

    # Genera un output haciendo la suma de los valores de input multiplicados por su peso sinaptico, y aplicandole la función sigmoide para normalizar a -1, 1
    outputs = forward(input_layer, synaptic_weights)

    # Calculo el error
    error = training_outputs - outputs

    # Ajusto los pesos en funcion al error y al resultado obtenido
    adjustments = error * sigmoid_derivative(outputs)
    synaptic_weights += np.dot(input_layer.T, adjustments)

C:\Users\gaetf\AppData\Local\Temp\ipykernel_19092\4196915625.py:2: RuntimeWarning: overflow encountered in exp
  return 1 / ( 1 + np.exp(-x) )
C:\Users\gaetf\AppData\Local\Temp\ipykernel_19092\4196915625.py:2: RuntimeWarning: overflow encountered in exp
  return 1 / ( 1 + np.exp(-x) )
C:\Users\gaetf\AppData\Local\Temp\ipykernel_19092\4196915625.py:2: RuntimeWarning: overflow encountered in exp
  return 1 / ( 1 + np.exp(-x) )
C:\Users\gaetf\AppData\Local\Temp\ipykernel_19092\4196915625.py:2: RuntimeWarning: overflow encountered in exp
  return 1 / ( 1 + np.exp(-x) )
C:\Users\gaetf\AppData\Local\Temp\ipykernel_19092\4196915625.py:2: RuntimeWarning: overflow encountered in exp
  return 1 / ( 1 + np.exp(-x) )
C:\Users\gaetf\AppData\Local\Temp\ipykernel_19092\4196915625.py:2: RuntimeWarning: overflow encountered in exp
  return 1 / ( 1 + np.exp(-x) )
C:\Users\gaetf\AppData\Local\Temp\ipykernel_19092\4196915625.py:2: RuntimeWarning: overflow encountered in exp
  return 1 / ( 1 + np.exp(-x) )

In [201]:
print('Synaptic weights after training')
print(synaptic_weights)

print('Outputs after training: ')
print(outputs)

Synaptic weights after training
[[-0.16595599  0.44064899 -0.99977125]
 [-0.39533485 -0.70648822 -0.81532281]
 [-0.62747958 -0.30887855 -0.20646505]
 [ 0.07763347 -0.16161097  0.370439  ]
 [-0.5910955   0.75623487 -0.94522481]]
Outputs after training: 
[[0. 1. 0.]
 [0. 1. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 1. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 1. 0.]
 [0. 0. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 0. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


EVALUACIÓN

In [202]:
table(training_values)

In [203]:
a = 0 #@param {type:"integer"}
b = 0 #@param {type:"integer"}
c = 0 #@param {type:"integer"}
d = 0 #@param {type:"integer"}
e = 0 #@param {type:"integer"}


input_layer = np.array([a, b, c, d, e])
res = sigmoid(np.dot(input_layer, synaptic_weights))

thresh = 0.01
out = np.where(res < thresh, 0, 1)

large(out)