In [1]:
%pip install numpy

Note: you may need to restart the kernel to use updated packages.


In [2]:
import numpy as np

In [4]:
X= np.random.rand(6,3) * 10
X = np.round(X, 2)
X

array([[2.25, 5.28, 5.63],
       [9.79, 5.56, 2.92],
       [0.05, 2.11, 1.23],
       [5.79, 5.51, 2.7 ],
       [0.76, 9.78, 0.22],
       [3.49, 4.32, 3.43]])

In [6]:
y = np.random.randint(0,2,6).reshape(-1,1)
y

array([[0],
       [0],
       [0],
       [0],
       [0],
       [1]], dtype=int32)

In [7]:
W = np.random.rand (4,1)
W

array([[0.60982722],
       [0.18062692],
       [0.02836844],
       [0.4501758 ]])

In [ ]:
def sigmoid():
    

In [9]:
ones = np.ones((X.shape[0], 1))
z = sigmoid(np.hstack(ones, X) @ W)
z

TypeError: hstack() takes 1 positional argument but 2 were given